-- Plugin providing functionality similar to Obsidian
--
-- See https://github.com/obsidian-nvim/obsidian.nvim (community-maintained fork of epwalsh/obsidian.nvim)

-- As of v3.1x, every `:Obsidian new` clones `opts.note.template` to disk *before*
-- `frontmatter.func` runs, so `note.path:is_file()` is always true by then and can no
-- longer be used to detect "this note is being created right now". `callbacks.create_note`
-- fires earlier, while the note is still only in memory, so it's used to mark genuinely new
-- paths here; `frontmatter.func` below consults (and clears) that mark instead of the stale
-- file-existence check.
local newly_created_note_paths = {}

return {
  'obsidian-nvim/obsidian.nvim',
  version = 'v3.16.7', -- recommended, use latest release instead of latest commit
  lazy = true,
  ft = 'markdown',
  -- Replace the above line with this if you only want to load obsidian.nvim for markdown files in your vault:
  -- event = {
  --   -- If you want to use the home shortcut '~' here you need to call 'vim.fn.expand'.
  --   -- E.g. "BufReadPre " .. vim.fn.expand "~" .. "/my-vault/**.md"
  --   "BufReadPre path/to/my-vault/**.md",
  --   "BufNewFile path/to/my-vault/**.md",
  -- },
  dependencies = {
    'nvim-lua/plenary.nvim',
    'hrsh7th/nvim-cmp', -- optional
    'nvim-telescope/telescope.nvim', -- optional
    'nvim-treesitter', -- optional
  },
  keys = {
    { '<leader>os', '<cmd>Obsidian search<cr>', desc = '[O]bsidian [S]earch' },
    { '<leader>oq', '<cmd>Obsidian quick_switch<cr>', desc = '[O]bsidian [Q]uick Switch' },
    { '<leader>on', ':Obsidian new', desc = '[O]bsidian [N]ew Note' },
    { '<leader>ob', '<cmd>Obsidian backlinks<cr>', desc = '[O]bsidian [B]acklinks' },
    { '<leader>ot', '<cmd>Obsidian tags<cr>', desc = '[O]bsidian [T]ags' },
    { '<leader>od', '<cmd>Obsidian dailies<cr>', desc = '[O]bsidian [D]ailies' },
    { '<leader>ol', ':Obsidian link', mode = { 'v' }, desc = '[O]bsidian [L]ink' },
    { '<leader>or', ':Obsidian rename', desc = '[O]bsidian [R]ename' },
    { '<leader>oo', '<cmd>Obsidian open<cr>', desc = '[O]bsidian [O]pen' },
    { '<leader>op', ':Obsidian paste_img', desc = '[O]bsidian [P]aste Image' },
    { '<leader>oW', '<cmd>Obsidian workspace<cr>', desc = '[O]bsidian [W]orkspace' },
    { '<leader>oT', '<cmd>Obsidian template<cr>', desc = '[O]bsidian [T]emplate' },
    {
      '<leader>ow',
      function()
        local year = vim.fn.system [[date +'%Y-W' | tr -d '\n']]
        local week = tonumber(vim.fn.system [[date +'%U' | tr -d '\n']]) + 1
        local id = 'Weekly Notes/' .. year .. week
        -- `:Obsidian new` ignores per-folder templates and always clones the global
        -- default, so the weekly template (and its `weekly-notes` tag) has to be
        -- requested explicitly via new_from_template.
        require('obsidian.actions').new_from_template(id, 'Weekly Note', function(note)
          note:open { sync = true }
        end)
      end,
      desc = '[O]bsidian [W]eekly Note',
    },
  },
  opts = {
    legacy_commands = false,

    -- Template used by `:Obsidian new` (and anything else that doesn't request a
    -- specific template) to seed new notes. Only supplies the `# {{title}}` header;
    -- frontmatter is regenerated by frontmatter.func below regardless of what the
    -- template itself writes.
    note = {
      template = 'New Note.md',
    },

    frontmatter = {
      -- UPDATED: Disable frontmatter for files in .claude/ OR named CLAUDE.md
      enabled = function(fname)
        if fname then
          local is_claude_dir = string.find(fname, '%.claude') ~= nil
          local is_claude_file = string.find(fname, 'CLAUDE%.md$') ~= nil

          if is_claude_dir or is_claude_file then
            return false
          end
        end
        return true
      end,

      -- Stamp every note with a system-managed `created` frontmatter field, matching the ISO 8601
      -- UTC timestamp moneta-notes' core/notes.js writes on note creation (see docs/specs/S003-notes.md).
      -- Replicates obsidian.nvim's default frontmatter (id, aliases, tags, then any other metadata) and
      -- only fills in `created` when this really is a creation, not just any save where the field
      -- happens to be missing. This func runs on every save (first and subsequent), and plenty of
      -- pre-existing notes have no `created` key at all; checking "does metadata.created exist" instead
      -- would stamp today's date onto one of those the next time it's merely edited, fabricating a
      -- false creation time. Newness comes from `newly_created_note_paths` (set in callbacks.create_note
      -- above) rather than `note.path:is_file()`, since the note's template is cloned to disk before
      -- this func runs, so the file already exists by the time we'd check it.
      ---@param note obsidian.Note
      ---@return table
      func = function(note)
        local out = { id = note.id, aliases = note.aliases, tags = note.tags }
        if note.metadata ~= nil and not vim.tbl_isempty(note.metadata) then
          for k, v in pairs(note.metadata) do
            out[k] = v
          end
        end
        local path_key = note.path and tostring(note.path)
        local is_new_note = path_key ~= nil and newly_created_note_paths[path_key] == true
        if out.created == nil and is_new_note then
          out.created = os.date '!%Y-%m-%dT%H:%M:%SZ'
        end
        return out
      end,
    },

    callbacks = {
      -- Fires while the note is still only in memory, before any template is cloned to disk —
      -- see the comment on `newly_created_note_paths` above. `note:write()` calls
      -- `frontmatter.func` twice synchronously per write (once directly, once again inside
      -- `save()`, which ignores the first result and recomputes — a quirk of the plugin, not
      -- something we control), so the mark can't be cleared inside `func` itself or the second
      -- call would see it gone. Deferring the clear to the next tick lets both calls in a
      -- single write see the mark while still clearing it before any later, genuinely separate
      -- save of the same note.
      create_note = function(note)
        if note.path then
          local path_key = tostring(note.path)
          newly_created_note_paths[path_key] = true
          vim.schedule(function()
            newly_created_note_paths[path_key] = nil
          end)
        end
      end,
    },

    -- Optional, completion of wiki links, local markdown links, and tags.
    -- Now provided via obsidian.nvim's built-in LSP server (obsidian-ls), picked up
    -- automatically through the existing nvim_lsp cmp source.
    completion = {
      -- Trigger completion at 2 chars.
      min_chars = 2,
    },

    -- Optional, customize how note IDs are generated given an optional title.
    ---@param title string|?
    ---@return string
    note_id_func = function(title)
      -- Create note IDs in a Zettelkasten format with a timestamp and a suffix.
      -- In this case a note with the title 'My new note' will be given an ID that looks
      -- like '1657296016-my-new-note', and therefore the file name '1657296016-my-new-note.md'
      local suffix = ''
      if title ~= nil then
        return title
        -- If title is given, transform it into valid file name.
        -- suffix = title:gsub(" ", "-"):gsub("[^A-Za-z0-9-]", ""):lower()
      else
        -- If title is nil, just add 4 random uppercase letters to the suffix.
        for _ = 1, 4 do
          suffix = suffix .. string.char(math.random(65, 90))
        end
      end
      return tostring(os.time()) .. '-' .. suffix
    end,

    -- create new notes in the root directory
    notes_subdir = '.',
    new_notes_location = 'notes_subdir',

    picker = {
      -- Set your preferred picker. Can be one of 'telescope.nvim', 'fzf-lua', or 'mini.pick'.
      name = 'telescope.nvim',
      -- Optional, configure key mappings for the picker. These are the defaults.
      -- Not all pickers support all mappings.
      note_mappings = {
        -- Create a new note from your query.
        new = '<C-x>',
        -- Insert a link to the selected note.
        insert_link = '<C-l>',
      },
    },

    checkbox = {
      order = { ' ', '/', 'x', '-', '!' },
    },

    ui = {
      checkboxes = {
        [' '] = { order = 1, char = '󰄱', hl_group = 'ObsidianTodo' },
        ['/'] = { order = 3, char = '', hl_group = 'ObsidianRightArrow' },
        ['x'] = { order = 2, char = '', hl_group = 'ObsidianDone' },
        ['-'] = { order = 4, char = '', hl_group = 'ObsidianTilde' },
        ['!'] = { order = 5, char = '', hl_group = 'ObsidianImportant' },
      },
    },
  },
  config = function(_, opts)
    local localConfig = require 'local.obsidian'

    for k, v in pairs(localConfig) do
      opts[k] = v
    end

    -- Silence obsidian.nvim's "ui.checkboxes no longer affects ordering" notice: `ui.checkboxes`
    -- is still the only way to set custom checkbox glyphs/highlights (order comes from
    -- `checkbox.order` above), so the warning is unconditional and permanent by design
    -- (maintainer confirmed no way to opt out: https://github.com/obsidian-nvim/obsidian.nvim/issues/262).
    if not vim.g.obsidian_ui_checkboxes_notify_filtered then
      vim.g.obsidian_ui_checkboxes_notify_filtered = true
      local orig_notify = vim.notify
      vim.notify = function(msg, level, notify_opts)
        if type(msg) == 'string' and msg:find("ui.checkboxes' no longer effect", 1, true) then
          return
        end
        return orig_notify(msg, level, notify_opts)
      end
    end

    require('obsidian').setup(opts)
  end,
}
